#!/usr/bin/env bash
# Built & run in production by the Agents Deployed team — https://agents-deployed.com
# embed.sh — regenerate the EMBEDDED RELAY PAYLOAD block inside bin/floo-powder from the canonical
# relay/ sources, so floo-powder is a single self-contained operator file (curl|bash, no git clone)
# while relay/{floo-route,floo-authkeys,install-relay.sh} remain the unit-tested source of truth.
#
#   scripts/embed.sh           re-embed (rewrite bin/floo-powder in place)
#   scripts/embed.sh --check   verify the embedded copy matches relay/ source; exit 1 on drift
#
# Wired into test/run-all.sh (--check) so the suite fails loudly if a relay/ file is edited without
# re-embedding. base64 (not heredocs) is used because the relay scripts contain their own heredocs.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
POWDER="$ROOT/bin/floo-powder"
BEGIN="# ── BEGIN EMBEDDED RELAY PAYLOAD"
END="# ── END EMBEDDED RELAY PAYLOAD ──"

for f in floo-route floo-authkeys install-relay.sh; do
  [ -f "$ROOT/relay/$f" ] || { echo "embed: missing relay/$f" >&2; exit 1; }
done

gen() {
  echo "$BEGIN (generated by scripts/embed.sh from relay/ — DO NOT EDIT BY HAND; re-run scripts/embed.sh) ──"
  echo "FLOO_EMBED_ROUTE_B64='$(base64 -w0 "$ROOT/relay/floo-route")'"
  echo "FLOO_EMBED_AUTHKEYS_B64='$(base64 -w0 "$ROOT/relay/floo-authkeys")'"
  echo "FLOO_EMBED_INSTALL_RELAY_B64='$(base64 -w0 "$ROOT/relay/install-relay.sh")'"
  echo "$END"
}

# the current block as it stands in bin/floo-powder (BEGIN..END inclusive)
current() { awk -v b="BEGIN EMBEDDED RELAY PAYLOAD" -v e="END EMBEDDED RELAY PAYLOAD" \
  '$0 ~ b {f=1} f {print} $0 ~ e {f=0}' "$POWDER"; }

if [ "${1:-}" = --check ]; then
  if [ "$(current)" = "$(gen)" ]; then echo "embed: in sync with relay/ source"; exit 0; fi
  echo "embed: DRIFT — bin/floo-powder embedded payload differs from relay/ source. Run scripts/embed.sh" >&2
  exit 1
fi

grep -qF "BEGIN EMBEDDED RELAY PAYLOAD" "$POWDER" || { echo "embed: no payload markers in $POWDER" >&2; exit 1; }
repl="$(gen)"
awk -v repl="$repl" \
  '$0 ~ "BEGIN EMBEDDED RELAY PAYLOAD" {print repl; skip=1} $0 ~ "END EMBEDDED RELAY PAYLOAD" {skip=0; next} !skip {print}' \
  "$POWDER" > "$POWDER.tmp"
mv "$POWDER.tmp" "$POWDER"
chmod +x "$POWDER"
echo "embed: bin/floo-powder re-embedded from relay/ ($(wc -c < "$POWDER") bytes)"
