#!/usr/bin/env bash
# Built & run in production by the Agents Deployed team — https://agents-deployed.com
# embed.sh — regenerate the EMBEDDED RELAY PAYLOAD block inside bin/floo-powder from the canonical
# relay/ sources, so floo-powder is a single self-contained operator file (curl|bash, no git clone)
# WHILE STAYING FULLY READABLE — the relay is embedded as verbatim bash via quoted heredocs, not
# base64, so an operator can `less floo-powder` and read exactly what `init` writes out and sudo-runs.
# relay/{floo-route,floo-authkeys,install-relay.sh} remain the unit-tested source of truth.
#
#   scripts/embed.sh           re-embed (rewrite bin/floo-powder in place)
#   scripts/embed.sh --check   verify the embedded copy matches relay/ source; exit 1 on drift
#
# Wired into test/run-all.sh (--check) so the suite fails loudly if a relay/ file is edited without
# re-embedding. Quoted heredocs (<<'DELIM') reproduce each file byte-for-byte (no expansion); the
# delimiters below can't collide with the relay scripts' own heredocs (CFG/UNIT/JAIL).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
POWDER="$ROOT/bin/floo-powder"
BEGIN="# ── BEGIN EMBEDDED RELAY PAYLOAD"
END="# ── END EMBEDDED RELAY PAYLOAD ──"

for f in floo-route floo-authkeys install-relay.sh; do
  [ -f "$ROOT/relay/$f" ] || { echo "embed: missing relay/$f" >&2; exit 1; }
done

# one `cat > "$d/<file>" <<'DELIM' … DELIM` block, with the relay source inlined verbatim.
emit_one() {
  local f="$1" delim="$2"
  if grep -qxF "$delim" "$ROOT/relay/$f"; then
    echo "embed: delimiter $delim collides with a line in relay/$f — pick another" >&2; exit 1
  fi
  printf '  cat > "$d/%s" <<'\''%s'\''\n' "$f" "$delim"   # the heredoc body is NOT expanded
  cat "$ROOT/relay/$f"
  printf '%s\n' "$delim"                                  # closing delimiter MUST be column 0
}

gen() {
  printf '%s (generated by scripts/embed.sh from relay/ — readable on purpose; DO NOT EDIT BY HAND; re-run scripts/embed.sh) ──\n' "$BEGIN"
  printf '# The relay below is VERBATIM from relay/{floo-route,floo-authkeys,install-relay.sh} — the same code\n'
  printf '# as in the repo. `floo-powder init` writes these out and sudo-runs install-relay.sh; read them.\n'
  printf 'materialize_relay() {\n'
  printf '  local d="$1"; mkdir -p "$d"\n'
  emit_one floo-route       FLOO_EMBED_EOF_ROUTE
  emit_one floo-authkeys    FLOO_EMBED_EOF_AUTHKEYS
  emit_one install-relay.sh FLOO_EMBED_EOF_INSTALL
  printf '  chmod +x "$d/floo-route" "$d/floo-authkeys" "$d/install-relay.sh"\n'
  printf '}\n'
  printf '%s\n' "$END"
}

# the current block as it stands in bin/floo-powder (BEGIN..END inclusive)
current() { awk '/BEGIN EMBEDDED RELAY PAYLOAD/{f=1} f{print} /END EMBEDDED RELAY PAYLOAD/{f=0}' "$POWDER"; }

if [ "${1:-}" = --check ]; then
  if [ "$(current)" = "$(gen)" ]; then echo "embed: in sync with relay/ source"; exit 0; fi
  echo "embed: DRIFT — bin/floo-powder embedded payload differs from relay/ source. Run scripts/embed.sh" >&2
  exit 1
fi

grep -qF "BEGIN EMBEDDED RELAY PAYLOAD" "$POWDER" || { echo "embed: no payload markers in $POWDER" >&2; exit 1; }
# Splice via a temp file read with getline (NOT awk -v — the relay source contains backslashes like
# \b that awk -v would mangle). Replace everything between the BEGIN and END markers with gen().
repl="$(mktemp)"; trap 'rm -f "$repl"' EXIT
gen > "$repl"
awk -v rf="$repl" '
  /BEGIN EMBEDDED RELAY PAYLOAD/ { while ((getline line < rf) > 0) print line; close(rf); skip=1; next }
  /END EMBEDDED RELAY PAYLOAD/   { skip=0; next }
  !skip { print }
' "$POWDER" > "$POWDER.tmp"
mv "$POWDER.tmp" "$POWDER"
chmod +x "$POWDER"
echo "embed: bin/floo-powder re-embedded from relay/ ($(wc -c < "$POWDER") bytes, readable heredocs)"
